# Generated by Django 4.0.5 on 2022-07-06 07:14
from django.db import migrations, models
from django.template.defaultfilters import slugify

DEFAULT="666"

def forwards(apps, _):
    Persona = apps.get_model("personas", "Persona")
    personas = Persona.objects.all()
    for persona in personas:
        persona.slug = slugify(persona.telefono)
        persona.save()


def backwards(apps, _):
    Persona = apps.get_model("personas", "Persona")
    personas = Persona.objects.all()
    for persona in personas:
        persona.slug = DEFAULT
        persona.save()


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]


    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=DEFAULT, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards)
    ]
